services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: fastrankingcrm_app

    ports:
      - "8000:8000"

    volumes:
      - .:/var/www/html

    depends_on:
      - mysql

    working_dir: /var/www/html

    networks:
      - fastranking-network

  mysql:
    image: mysql:8.0

    container_name: fastrankingcrm_mysql

    restart: unless-stopped

    ports:
      - "3307:3306"

    environment:
      MYSQL_DATABASE: fastrankingcrm
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - fastranking-network

  phpmyadmin:
    image: phpmyadmin:latest

    container_name: fastrankingcrm_phpmyadmin

    restart: unless-stopped

    ports:
      - "8080:80"

    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

    depends_on:
      - mysql

    networks:
      - fastranking-network

volumes:
  mysql_data:

networks:
  fastranking-network:
    external: true